return {
	START_MOVEMENT = 1,
	STOP_MOVEMENT = 2,
	UPDATE_MOVEMENT = 3,
	INCREMENT_POSITION = 4,
	SET_POSITION = 5,
	START_MOVEMENT_CUSTOM = 6,
	STOP_MOVEMENT_CUSTOM = 7,
	RESET_MOVEMENT = 8,
	RESET_MOVEMENT_CUSTOM = 9,
}