local ACTION = {}

ACTION.SET_ID = {
	PLAYER_MAIN = 1,
	GENERIC_AREA = 2,
	GENERIC_EMITTER = 3
}

ACTION.ACTION_ID = {
	[ACTION.SET_ID.PLAYER_MAIN] = {
		GENERIC = 1,
		IDLE = 2,
		DESPAWN_TEST = 3,
		INTERACT_TEST = 4,
		COMBAT_TEST = 5,
		COMBAT_RANGED = 6,
		KNOCKBACK_TEST = 7,
	},
	[ACTION.SET_ID.GENERIC_AREA] = {
		GENERIC = 1,
		CHANGE_AREA = 2,
		ELEVATOR = 3,
		CHEST = 4,
		DOOR = 5
	},
	[ACTION.SET_ID.GENERIC_EMITTER] = {
		GENERIC = 1,
		GLOBAL = 2,
	},
}

return ACTION