return {
	NONE = 'none',
	MOVE_UP = 'move_up',
	MOVE_LEFT = 'move_left',
	MOVE_DOWN = 'move_down',
	MOVE_RIGHT = 'move_right',
	END_MOVE_UP = 'end_move_up',
	END_MOVE_LEFT = 'end_move_left',
	END_MOVE_DOWN = 'end_move_down',
	END_MOVE_RIGHT = 'end_move_right',
	SET_TARGETING_STATE = 'set_targeting_state',
	SEARCH_TARGET = 'search_target',
	INTERACT_REQUEST = 'interact_request',
	ATTACK_A = 'attack_a',
	ATTACK_B = 'attack_b',
	ATTACK_C = 'attack_c',
	CONTINUE_ATTACK_A = 'continue_attack_a',
	CONTINUE_ATTACK_B = 'continue_attack_b',
	CONTINUE_ATTACK_C = 'continue_attack_c',
	END_ATTACK = 'end_attack',
	SPECIAL_MOVE = 'special_move',
}