return {
	ATTACK_SLOT_A = 1,
	ATTACK_SLOT_B = 2,
	ATTACK_SLOT_C = 3,
	ATTACK_MELEE = 4,
	ATTACK_RANGED = 5,
	ATTACK_INDEX = 6,
	ATTACK_CUSTOM = 7,
	LOCKUP = 8,
	KNOCKBACK = 9,
	SPECIAL_MOVE = 10,
	SPECIAL_ATTACK = 11,
	END_ATTACK = 12,
	END_COMBAT = 13
}