local DATABASE_COLUMN = {}

--GENERIC ENTITY (can be used for pretty much anything, even walls - really cool)
--deprecated - thank god!

DATABASE_COLUMN.GLOBAL_TABLE_ID = 1
DATABASE_COLUMN.GLOBAL_TABLE_SCENE = 1
DATABASE_COLUMN.GLOBAL_TABLE_SPRITE = 1
DATABASE_COLUMN.GLOBAL_TABLE_IDLE = 1
DATABASE_COLUMN.GLOBAL_TABLE_HITBOX = 1
DATABASE_COLUMN.GLOBAL_TABLE_ACTION = 1
DATABASE_COLUMN.GLOBAL_TABLE_INPUT = 1
DATABASE_COLUMN.GLOBAL_TABLE_MOVEMENT = 1
DATABASE_COLUMN.GLOBAL_TABLE_TARGETING = 1

DATABASE_COLUMN.SCENE_TABLE_PARENT_1 = 1
DATABASE_COLUMN.SCENE_TABLE_DEFAULT_ROLE = 2
DATABASE_COLUMN.SCENE_TABLE_ROLE = 3
DATABASE_COLUMN.SCENE_TABLE_SPRITEBOX_INDEX = 4

DATABASE_COLUMN.STATE_TABLE_PARENT_1 = 1
DATABASE_COLUMN.STATE_TABLE_HITBOX_ROW_INDEX = 2
DATABASE_COLUMN.STATE_TABLE_GLOBAL_ENTITY_STATE = 3
DATABASE_COLUMN.STATE_TABLE_DEFAULT_ENTITY_STATE = 4
DATABASE_COLUMN.STATE_TABLE_INPUT_ROW_INDEX = 5
DATABASE_COLUMN.STATE_TABLE_MOVEMENT_ROW_INDEX = 6

DATABASE_COLUMN.INPUT_TABLE_PARENT_1 = 1
DATABASE_COLUMN.INPUT_TABLE_STATE_ROW_INDEX = 2
DATABASE_COLUMN.INPUT_TABLE_INPUT_STATE = 3

DATABASE_COLUMN.SPRITEBOX_TABLE_PARENT_1 = 1
DATABASE_COLUMN.SPRITEBOX_TABLE_PARENT_2 = 2
DATABASE_COLUMN.SPRITEBOX_TABLE_X = 3
DATABASE_COLUMN.SPRITEBOX_TABLE_Y = 4
DATABASE_COLUMN.SPRITEBOX_TABLE_W = 5
DATABASE_COLUMN.SPRITEBOX_TABLE_H = 6
DATABASE_COLUMN.SPRITEBOX_TABLE_DEFAULT_SPRITESHEET_ID = 7
DATABASE_COLUMN.SPRITEBOX_TABLE_SPRITESHEET_ID = 8
DATABASE_COLUMN.SPRITEBOX_TABLE_QUAD = 9
DATABASE_COLUMN.SPRITEBOX_TABLE_ANI_REPO_ID = 10
DATABASE_COLUMN.SPRITEBOX_TABLE_HITBOX_INDEX = 11
DATABASE_COLUMN.SPRITEBOX_TABLE_IDLE_INDEX = 12

DATABASE_COLUMN.HITBOX_TABLE_PARENT_1 = 1
DATABASE_COLUMN.HITBOX_TABLE_SPRITEBOX_INDEX = 2
DATABASE_COLUMN.HITBOX_TABLE_X = 3
DATABASE_COLUMN.HITBOX_TABLE_Y = 4
DATABASE_COLUMN.HITBOX_TABLE_W = 5
DATABASE_COLUMN.HITBOX_TABLE_H = 6
DATABASE_COLUMN.HITBOX_TABLE_MAP_COLLISION_TYPE = 7
DATABASE_COLUMN.HITBOX_TABLE_ENTITY_COLLISION_TYPE = 8

DATABASE_COLUMN.ANIMATED_IDLE_TABLE_GLOBAL_ENTITY_ROW_INDEX = 1
DATABASE_COLUMN.ANIMATED_IDLE_TABLE_SPRITE_BOX_ROW_INDEX = 2
DATABASE_COLUMN.ANIMATED_IDLE_TABLE_STATE = 3
DATABASE_COLUMN.ANIMATED_IDLE_TABLE_SPRITE_ANIMATION_ID = 4
DATABASE_COLUMN.ANIMATED_IDLE_TABLE_DEFAULT_QUAD = 5
DATABASE_COLUMN.ANIMATED_IDLE_TABLE_TOTAL_TIME = 6
DATABASE_COLUMN.ANIMATED_IDLE_TABLE_CURRENT_TIME = 7
DATABASE_COLUMN.ANIMATED_IDLE_TABLE_FREQUENCY = 8
DATABASE_COLUMN.ANIMATED_IDLE_TABLE_UPDATE_POINT = 9

DATABASE_COLUMN.MOVEMENT_TABLE_PARENT_1 = 1
DATABASE_COLUMN.MOVEMENT_TABLE_STATE_INDEX = 2
DATABASE_COLUMN.MOVEMENT_TABLE_VELOCITY = 3
DATABASE_COLUMN.MOVEMENT_TABLE_DIRECTION = 4
DATABASE_COLUMN.MOVEMENT_TABLE_SPRITESHEET_ID = 5
DATABASE_COLUMN.MOVEMENT_TABLE_DEFAULT_QUAD = 6
DATABASE_COLUMN.MOVEMENT_TABLE_TOTAL_TIME = 7
DATABASE_COLUMN.MOVEMENT_TABLE_CURRENT_TIME = 8
DATABASE_COLUMN.MOVEMENT_TABLE_FREQUENCY = 9
DATABASE_COLUMN.MOVEMENT_TABLE_UPDATE_POINT = 10
DATABASE_COLUMN.MOVEMENT_TABLE_MOVEMENT_REPO_ID = 11

DATABASE_COLUMN.TARGETING_TABLE_PARENT_1 = 1
DATABASE_COLUMN.TARGETING_TABLE_PARENT_2 = 2
DATABASE_COLUMN.TARGETING_TABLE_STATE_INDEX = 3
DATABASE_COLUMN.TARGETING_TABLE_DEFAULT_TARGETING_TYPE = 4
DATABASE_COLUMN.TARGETING_TABLE_TARGETING_TYPE = 5
DATABASE_COLUMN.TARGETING_TABLE_AREA_RADIUS = 6
DATABASE_COLUMN.TARGETING_TABLE_TARGET_ENTITY_TYPE = 7
DATABASE_COLUMN.TARGETING_TABLE_TARGET_ENTITY_REF = 8

--WALLS:

DATABASE_COLUMN.GENERIC_OBSTACLE_QUAD_GLOBAL_ID = 1
DATABASE_COLUMN.GENERIC_OBSTACLE_QUAD_X = 2
DATABASE_COLUMN.GENERIC_OBSTACLE_QUAD_Y = 3
DATABASE_COLUMN.GENERIC_OBSTACLE_QUAD_W = 4
DATABASE_COLUMN.GENERIC_OBSTACLE_QUAD_H = 5

return DATABASE_COLUMN