local EVENT_OBJECT = {}

EVENT_OBJECT.TARGETING_REQUEST_TYPE = 1
EVENT_OBJECT.TARGETING_SELECTOR_ENTITY_TYPE = 2
EVENT_OBJECT.TARGETING_SELECTOR_ENTITY = 3
EVENT_OBJECT.TARGETING_STATE = 4
EVENT_OBJECT.TARGETING_TARGET_ENTITY_LIST = 5
--(...)

return EVENT_OBJECT