local PROJECTILE_TYPE = {}

PROJECTILE_TYPE.PROJECTILE_CONTROLLER = require 'PROJECTILE_CONTROLLER'
PROJECTILE_TYPE.PROJECTILE_DESTRUCTOR = require 'PROJECTILE_DESTRUCTOR'
PROJECTILE_TYPE.CONTROLLER_TYPES = PROJECTILE_TYPE.PROJECTILE_CONTROLLER.TYPES
PROJECTILE_TYPE.DESTRUCTOR_TYPES = PROJECTILE_TYPE.PROJECTILE_DESTRUCTOR.TYPES

PROJECTILE_TYPE.TYPES = {
	GENERIC = 1
}

PROJECTILE_TYPE.TEMPLATE_TYPES = {
	GENERIC = 1,
}

PROJECTILE_TYPE.TEMPLATES = {
	[PROJECTILE_TYPE.TEMPLATE_TYPES.GENERIC] = {
		projectileType = PROJECTILE_TYPE.TYPES.GENERIC,
		w = 0,
		h = 0,
		velocity = 2,
		spritesheetId = 1,
		spritesheetQuad = 1,
		spriteOffsetX = 12,
		spriteOffsetY = 12,
		controller = PROJECTILE_TYPE.CONTROLLER_TYPES.GENERIC,
		destructor = PROJECTILE_TYPE.DESTRUCTOR_TYPES.GENERIC,
		animation = 1
	}
	
	--...
}

return PROJECTILE_TYPE