local EVENT_TYPE = {}

EVENT_TYPE.GENERIC = 1
EVENT_TYPE.SPATIAL_REQUEST = 2
EVENT_TYPE.ANIMATION = 3
EVENT_TYPE.ACTION = 4
EVENT_TYPE.INTERACTION = 5
EVENT_TYPE.VISUAL_EFFECT = 6
EVENT_TYPE.START_STATE = 7
EVENT_TYPE.CHANGE_SCENE = 8
EVENT_TYPE.DATABASE_REQUEST = 9
EVENT_TYPE.INIT_SCENE = 10
EVENT_TYPE.INIT_ENTITY = 11
EVENT_TYPE.INIT_CAMERA = 12
EVENT_TYPE.SET_LENS = 13
EVENT_TYPE.INIT_AREA = 14
EVENT_TYPE.SET_GRAPHIC = 15
EVENT_TYPE.PLAYER_INPUT = 16
EVENT_TYPE.MOVEMENT = 17
EVENT_TYPE.IDLE = 18
EVENT_TYPE.SPATIAL_UPDATER = 19
EVENT_TYPE.TARGETING = 20
EVENT_TYPE.ENTITY_SPAWN = 21
EVENT_TYPE.ENTITY_DESPAWN = 22
EVENT_TYPE.ENTITY_SCRIPT = 23
EVENT_TYPE.ENTITY_INPUT = 24
EVENT_TYPE.ENTITY_EVENT = 25
EVENT_TYPE.SCENE_CHANGE = 25
EVENT_TYPE.SET_FLAG = 26
EVENT_TYPE.SET_INVENTORY = 27
EVENT_TYPE.ITEM = 28
EVENT_TYPE.SET_GAME_STATE = 29
EVENT_TYPE.ENTITY_COMBAT = 30
EVENT_TYPE.ENTITY_HEALTH = 31
EVENT_TYPE.PROJECTILE = 32

return EVENT_TYPE