local PROJECTILE_COMPONENT = {}

PROJECTILE_COMPONENT.MAIN = 1
PROJECTILE_COMPONENT.STATE = 2
PROJECTILE_COMPONENT.SCENE = 3
PROJECTILE_COMPONENT.SPATIAL = 4
PROJECTILE_COMPONENT.SPRITE = 5
PROJECTILE_COMPONENT.CONTROLLER = 6
--(...)

return PROJECTILE_COMPONENT