local ENTITY_COMPONENT = {}

ENTITY_COMPONENT.MAIN = 1
ENTITY_COMPONENT.SCENE = 2
ENTITY_COMPONENT.SPRITEBOX = 3
ENTITY_COMPONENT.HITBOX = 4
ENTITY_COMPONENT.ACTION_STATE = 5
ENTITY_COMPONENT.PLAYER_INPUT = 6
ENTITY_COMPONENT.IDLE = 7
ENTITY_COMPONENT.MOVEMENT = 8
ENTITY_COMPONENT.TARGETING = 9
ENTITY_COMPONENT.TRANSPORT = 10
ENTITY_COMPONENT.ACTION = 11
ENTITY_COMPONENT.SPAWN = 12
ENTITY_COMPONENT.DESPAWN = 13
ENTITY_COMPONENT.SCRIPT = 14
ENTITY_COMPONENT.EVENT = 15
ENTITY_COMPONENT.ITEM = 16
ENTITY_COMPONENT.INVENTORY = 17
ENTITY_COMPONENT.COMBAT = 18
ENTITY_COMPONENT.HEALTH = 19
ENTITY_COMPONENT.DIALOGUE = 20
--(...)

return ENTITY_COMPONENT