local ENTITY_TYPE = {}

ENTITY_TYPE.GENERIC_ENTITY = 1
ENTITY_TYPE.GENERIC_WALL = 2
ENTITY_TYPE.GENERIC_PROJECTILE = 3
ENTITY_TYPE.VISUAL_EFFECT = 4
ENTITY_TYPE.UNDEFINED = 5

--(...)

return ENTITY_TYPE