local ENTITY_ROLE = {}

ENTITY_ROLE.UNDEFINED = 1
ENTITY_ROLE.PLAYER = 2
ENTITY_ROLE.HOSTILE_NPC = 3
ENTITY_ROLE.OBSTACLE = 4		--VERY IMP: this role is indexed as entity type 'GENERIC_WALL'
ENTITY_ROLE.BULLET = 5
ENTITY_ROLE.VISUAL_EFFECT = 6
ENTITY_ROLE.BACKGROUND_OBJECT = 7
ENTITY_ROLE.ENTITY_EVENT = 8
ENTITY_ROLE.ITEM = 9
ENTITY_ROLE.FRIEND_PROJECTILE = 10
ENTITY_ROLE.HOSTILE_PROJECTILE = 11
ENTITY_ROLE.FOREGROUND_OBJECT = 12
--(...)

return ENTITY_ROLE