local SPATIAL_QUERY = {}

SPATIAL_QUERY.UPDATE_ENTITY = 1
SPATIAL_QUERY.GET_NEAREST_ENTITY_BY_AREA_AND_ROLE = 2
SPATIAL_QUERY.GET_COLLISION_PAIRS_IN_AREA = 3
SPATIAL_QUERY.GET_ENTITIES_IN_AREA_FOR_RENDERING = 4
SPATIAL_QUERY.REGISTER_ENTITY = 5
SPATIAL_QUERY.GET_ENTITIES_IN_AREA_BY_ROLE_LEGACY = 6
SPATIAL_QUERY.GET_ENTITIES_IN_AREA_BY_ROLE = 7
SPATIAL_QUERY.UNREGISTER_ENTITY = 8
SPATIAL_QUERY.REINDEX_ENTITY = 9

return SPATIAL_QUERY