local PROJECTILE_COMPONENT = {}

PROJECTILE_COMPONENT.MAIN = 1
PROJECTILE_COMPONENT.STATE = 2
PROJECTILE_COMPONENT.SCENE = 3
PROJECTILE_COMPONENT.SPATIAL = 4
PROJECTILE_COMPONENT.SPRITE = 5
PROJECTILE_COMPONENT.TARGET = 6
PROJECTILE_COMPONENT.ANIMATION = 7
PROJECTILE_COMPONENT.CONTROLLER = 8
PROJECTILE_COMPONENT.DESTRUCTOR = 9
--(...)

return PROJECTILE_COMPONENT