return {
	SPAWN = 1,
	DESPAWN = 2,
	MOVEMENT = 3,
	TARGETING = 4,
	EVENT = 5,
	COMBAT = 6,
	IDLE = 7,
	STOP_MOVEMENT = 8,
	STOP_IDLE = 9,
	START_MOVEMENT = 10,
	START_IDLE = 11,
	START_MOVEMENT_COMBAT = 12,
	START_IDLE_COMBAT = 13,
	--...
}